### ISSUE TITLE
Mancsérték megjelenítés

### ISSUE THREAD

**Issue by zalangyarmati** [mok-it/mok-app#108]
detailsfragmenten: mancsérték megjelenítés
listanézeten: mancsérték megjelenítés
saját mancsaim: megszerzett mancsérték megjelenítés

**Comment by notAnElephant** [comment]
fun fact: itt az első pont már meg is volt csinálva :D csak azért nem látszott, mert minden projekt 1 mancsot ért (az előző félévben legalábbis)
