### ISSUE TITLE
A mancsaim felület legtetején jelenjen meg egy összefoglalás a kötelező teendők állapotáról 

### ISSUE THREAD

**Issue by notAnElephant** [mok-it/mok-app#125]
ide értve azt is, hogy mennyi/mennyi kritikus és nem kritikus mancsa van az illetőnek

+ a teljesített egyéb feladatokat (versenyrészvétel, stb.)

**Comment by Tchallenge13** [comment]
A megbeszéltek szerint ez mégsem így fog kinézni. A mancsaim felület továbbra is a már teljesített dolgokról fog szólni, és egy külön "feladataim" felületen fognak megjelenni az említett adatok.
