### ISSUE TITLE
repó klónozása, app elindítása, ssh key hozzáadása

### ISSUE THREAD

**Issue by notAnElephant** [mok-it/mok-app#158]
- [x] klónozd a repót
- [x] futtasd az appot
- [x] konstatáld, hogy nem megy
- [x] generáld le az sha-kulcsod az alábbiak alapján az Android Studioban:

Select Gradle in android studio from right panel
Select Your App
In Tasks -> android-> signingReport
Double click signingReport.

You will find the SHA-1 fingerprint in the "Gradle Console
- [x] küldd el nekem a kapott fingerprinted

**Comment by matetamasi** [comment]
A "konstatáld hogy nem működik" részhez: Meg kéne nyílnia az appnak, lennie kell egy kék hátterű nézetnek amin van egy google login gomb. Ha megynyomod, akkor tudsz google accountot választani, de az után nem enged tovább.

Ha esetleg a signing task nem jelenne meg a gradle taskok közt, akkor settings > experimental > pipáld be hogy minden gradle task menjen és buildeld az appot.
