### ISSUE TITLE
Login levétele navigation backstackről

### ISSUE THREAD

**Issue by matetamasi** [mok-it/mok-app#159]
Első bejelentkezéskor a google login nézet ott marad a backstacken, így a vissza gomb nem zárja be az appot, hanem visszamegy a login oldalra, majd automatiusan továbbugrik a kezdőoldalra. A login ne maradjon rajta a backstacken, hogy ez ne forduljon elő.

**Comment by notAnElephant** [comment]
Kész. Két sor volt xml-ben :D annyit kellett megadni, hogy a loginfragment máshova dobjon visszanavigáláskor
