### ISSUE TITLE
Play áruház frissítések

### ISSUE THREAD

**Issue by matetamasi** [mok-it/mok-app#173]
Az app megnyitásakor a felhasználó kapjon egy figyelmeztetést ha az appra frissírtés érhető el. Kritikus fontosságú változtatás esetén (pl. ha az adatbázis "séma" módosul, és a korábbi hívások már nem értelmesek) az app frissítése legyen kötelező.

**Comment by notAnElephant** [comment]
ez elég sürgős lenne; viszonylag gyakran történik mostanában olyan, hogy dbséma változik, és elég kényelmetlen, ha a régi kliensek teleszemetelik a db-t a régi sémának megfelelően

**Comment by notAnElephant** [comment]
ezt #201 zárja? @matetamasi

**Comment by matetamasi** [comment]
Jó kérdés. Ezt nehéz értelmesen tesztelni, de amikor teszteltem, nem volt teljesen konzisztens a működése. Ez azért is lehet, mert maga a tesztelő rendszer sem mindig volt konzisztens. Elvileg zárja a a PR és helyes a kód, gyakorlatilag nem kizárt, hogy élesben ez fog meglepetéseket okozni. Annál rosszabb nem lehet, hogy az app szó nélkül matat tovább az adatbázisban a régi "séma" alapján, szóval nem annyira vészes a helyzet.

**Comment by matetamasi** [comment]
Jó kérdés. Ezt nehéz értelmesen tesztelni, de amikor teszteltem, nem volt teljesen konzisztens a működése. Ez azért is lehet, mert maga a tesztelő rendszer sem mindig volt konzisztens. Elvileg zárja a a PR és helyes a kód, gyakorlatilag nem kizárt, hogy élesben ez fog meglepetéseket okozni. Annál rosszabb nem lehet, hogy az app szó nélkül matat tovább az adatbázisban a régi "séma" alapján, szóval nem annyira vészes a helyzet.

**Comment by notAnElephant** [comment]
Oké, akkor zárom
