### ISSUE TITLE
remote config fix

### ISSUE THREAD

**Issue by notAnElephant** [mok-it/mok-app#198]
https://firebase.google.com/docs/remote-config/loading

3 stratégia van, jelenleg az elsőt használjuk, de ez nem túl jó megoldás. Részletesebben nincs kedvem leírni. Szar task.

**Comment by notAnElephant** [comment]
ennek előfeltétele a #5 is

**Comment by notAnElephant** [comment]
ez inkább fontos, mintsem sürgős, mert először a szezonváltásnál fog látszani, hogy nem lett jól kitalálva a dolog. 
Egy ilyen flow kéne amúgy: 
bejelentkezve:
loading -> allprojects
nem bejelentkezve:
login -> loading -> allprojects


és a loading alatt betölteni az usermodel(flow)t és a configértékeket is. Csak akkor menni tovább, ha mind2 betöltött

**Comment by matetamasi** [comment]
#201 ezt nagyrészt implementálja, az app indításakor az tölt és ilyenkor frissül a remote config. Elvileg nem lenne bonyolult bejelentkezés után is megcsinálni ugyanezt, illetve nem elkezdeni amíg nem vagyunk bejelentkezve.

**Comment by notAnElephant** [comment]
akkor zárom, mint wont implement
