### ISSUE TITLE
Admin felület

### ISSUE THREAD

**Issue by zalangyarmati** [mok-it/mok-app#2]
Megjelenítendő információk:
-adott kategóriákba kik tartoznak
-adott emberre rá lehessen keresni, hogy milyen badge-ei vannak

**Comment by notAnElephant** [comment]
Az első elavult, a másodikat lehetne implementalni (ugy, h megmutassa, milyen projektek tagja az illető, ill. Hany mancsot szerzett idáig rajtuk)

**Comment by notAnElephant** [comment]
web megoldja/meg fogja oldani
