### ISSUE TITLE
Kotlin syntheticsről ViewBindingre való teljes migrálás

### ISSUE THREAD

**Issue by notAnElephant** [mok-it/mok-app#68]
Ha vkit érdekel, itt a miértje: https://betterprogramming.pub/why-are-kotlin-synthetics-deprecated-and-what-are-the-alternatives-5c2b087dda1c

tldr: a viewbinding modernebb, type-safe és nem pollute-olja a a namespace-t sem (meg amúgy is, az app felében kb már azt használunk)

**Comment by notAnElephant** [comment]
@Tchallenge13 ebből akkor már csak a findViewById-k kiirtása van hátra?

**Comment by Tchallenge13** [comment]
Igen
