### ISSUE TITLE
Google analytics események logolása

### ISSUE THREAD

**Issue by notAnElephant** [mok-it/mok-app#83]
Jó lenne minél többet tudni a userek apphasználati szokásairól. Melyik menüpontot hányszor nyomják meg, melyek a legtöbbet megtekintett badge-ek, stb. Ehhez célszerű Google analyticset használni.

Hogy kell logolni: 
https://firebase.google.com/docs/analytics/get-started?technology=android&platform=android
Miket érdemes logolni:
https://support.google.com/firebase/answer/9267735?visit_id=638162362331652015-4291839242&rd=1

**Comment by notAnElephant** [comment]
@matetamasi ez hogy áll most? ha >50%, akkor lezárnám "not planned"-ként

**Comment by matetamasi** [comment]
0%, szerintem not planned, legalábbis egyelőre.
